apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomoto
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zomoto
  template:
    metadata:
      labels:
        app: zomoto
    spec:
      containers:
        - name: zomoto-container
          image: athult123/zomoto:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: zomoto-service
spec:
  selector:
    app: zomoto
  ports:
    - port: 3000
      targetPort: 3000
  type: NodePort
